/**
 * API Route: Manual Run Trigger
 * Allows triggering Russell 2000 runs from the GUI
 */

import { NextRequest, NextResponse } from 'next/server';
import { spawn } from 'child_process';
import path from 'path';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

interface TriggerRunRequest {
  universe?: string;
}

interface TriggerRunResponse {
  success: boolean;
  message: string;
  runId?: string;
  estimatedDuration?: string;
  error?: string;
}

export async function POST(request: NextRequest): Promise<NextResponse<TriggerRunResponse>> {
  try {
    const body = await request.json() as TriggerRunRequest;
    const universe = body.universe || 'russell2000_full_yf';

    // Estimate duration based on universe
    const estimatedDuration = universe.includes('russell2000_full')
      ? '15-25 minutes'
      : '5-10 minutes';

    // Run the daily script in background
    const scriptPath = path.join(process.cwd(), 'scripts', 'run_daily.ts');

    return new Promise((resolve) => {
      const child = spawn('npx', ['tsx', scriptPath, `--universe=${universe}`], {
        detached: true,
        stdio: 'ignore',
        cwd: process.cwd(),
      });

      // Don't wait for the process
      child.unref();

      resolve(
        NextResponse.json({
          success: true,
          message: `Run triggered for ${universe}`,
          estimatedDuration,
          runId: 'pending', // Will be generated by the script
        })
      );
    });
  } catch (error) {
    console.error('Failed to trigger run:', error);
    return NextResponse.json(
      {
        success: false,
        message: 'Failed to trigger run',
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

// GET endpoint to check if a run is currently in progress
export async function GET(): Promise<NextResponse> {
  // This is a simplified version - in production you'd check for a lock file or process
  return NextResponse.json({
    isRunning: false,
    message: 'No run status tracking implemented yet',
  });
}
